project:
  type: website
  output-dir: docs
website:
  title: "Jiahao's Websites"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd  
        text: Projects
      - href: blog.qmd
        text: Blog      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



